export const mockBills = [
  {
    id: '1',
    billNumber: 'BILL-001',
    vendor: 'Electric Company',
    amount: 1250.5,
    dueDate: '2024-02-15',
    status: 'paid',
    date: '2024-01-15',
    description: 'Monthly electricity bill',
  },
  {
    id: '2',
    billNumber: 'BILL-002',
    vendor: 'Water Authority',
    amount: 320.75,
    dueDate: '2024-02-20',
    status: 'pending',
    date: '2024-01-20',
    description: 'Monthly water bill',
  },
  {
    id: '3',
    billNumber: 'BILL-003',
    vendor: 'Internet Service',
    amount: 89.99,
    dueDate: '2024-02-01',
    status: 'overdue',
    date: '2024-01-01',
    description: 'Monthly internet subscription',
  },
  {
    id: '4',
    billNumber: 'BILL-004',
    vendor: 'Gas Company',
    amount: 450.25,
    dueDate: '2024-02-25',
    status: 'pending',
    date: '2024-01-25',
    description: 'Monthly gas bill',
  },
  {
    id: '5',
    billNumber: 'BILL-005',
    vendor: 'Property Management',
    amount: 2500.0,
    dueDate: '2024-02-05',
    status: 'paid',
    date: '2024-01-05',
    description: 'Monthly rent',
  },
]

export const mockDashboardMetrics = {
  totalBills: 142,
  pendingBills: 18,
  processingBills: 26,
  completedBills: 86,
  rejectedBills: 12,
}

export const mockBillHistory = [
  {
    id: 'bill-1024',
    billNumber: 'INV-1024',
    vendor: 'Northwind Logistics',
    category: 'Operations',
    amount: 3240.15,
    status: 'Submitted',
    billingDate: '2026-08-12',
    submittedBy: 'Priya Shah',
    description: 'Fuel and transport invoice for the month',
    documents: ['invoice-1024.pdf', 'receipt-1024.jpg'],
    timeline: [
      { status: 'Submitted', user: 'Priya Shah', date: '2026-08-12T09:15:00', note: 'Invoice uploaded and routed for review' },
      { status: 'In Review', user: 'David Lee', date: '2026-08-13T10:20:00', note: 'Vendor matching completed' },
    ],
  },
  {
    id: 'bill-1025',
    billNumber: 'INV-1025',
    vendor: 'Azure Grid Energy',
    category: 'Utilities',
    amount: 2147.8,
    status: 'Processing',
    billingDate: '2026-08-10',
    submittedBy: 'Alicia Morgan',
    description: 'Electricity and grid usage for headquarters',
    documents: ['energy-usage.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Alicia Morgan', date: '2026-08-10T14:00:00', note: 'Bill attached to finance queue' },
      { status: 'Processing', user: 'System', date: '2026-08-11T08:30:00', note: 'OCR extraction and validation in progress' },
    ],
  },
  {
    id: 'bill-1026',
    billNumber: 'INV-1026',
    vendor: 'Clearpeak SaaS',
    category: 'Software',
    amount: 980.0,
    status: 'Approved',
    billingDate: '2026-08-05',
    submittedBy: 'Emma Reed',
    description: 'Monthly SaaS subscription renewal',
    documents: ['clearpeak-subscription.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Emma Reed', date: '2026-08-05T11:20:00', note: 'Subscription renewal uploaded' },
      { status: 'Approved', user: 'David Lee', date: '2026-08-06T15:10:00', note: 'Approved after vendor verification' },
    ],
  },
  {
    id: 'bill-1027',
    billNumber: 'INV-1027',
    vendor: 'Summit Office Supply',
    category: 'Office Supplies',
    amount: 640.5,
    status: 'Rejected',
    billingDate: '2026-08-01',
    submittedBy: 'Priya Shah',
    description: 'Office printer cartridges and stationery',
    documents: ['office-supplies.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Priya Shah', date: '2026-08-01T09:00:00', note: 'Submitted for approval' },
      { status: 'Rejected', user: 'Alicia Morgan', date: '2026-08-02T16:00:00', note: 'Missing PO reference and approval code' },
    ],
  },
  {
    id: 'bill-1028',
    billNumber: 'INV-1028',
    vendor: 'Horizon Travel',
    category: 'Travel',
    amount: 1520.9,
    status: 'Paid',
    billingDate: '2026-07-28',
    submittedBy: 'David Lee',
    description: 'Quarterly travel and accommodation settlement',
    documents: ['travel-itinerary.pdf', 'hotel-summary.pdf'],
    timeline: [
      { status: 'Submitted', user: 'David Lee', date: '2026-07-28T08:45:00', note: 'Travel settlement submitted' },
      { status: 'Approved', user: 'Alicia Morgan', date: '2026-07-29T13:20:00', note: 'Expense approval matched policy' },
      { status: 'Paid', user: 'Finance Ops', date: '2026-07-31T17:30:00', note: 'Payment released via ACH transfer' },
    ],
  },
  {
    id: 'bill-1029',
    billNumber: 'INV-1029',
    vendor: 'Riverbank Telecom',
    category: 'Utilities',
    amount: 430.25,
    status: 'In Review',
    billingDate: '2026-08-15',
    submittedBy: 'Lucas Barnes',
    description: 'Broadband and mobile services',
    documents: ['riverbank-telecom.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Lucas Barnes', date: '2026-08-15T12:00:00', note: 'Invoice received and assigned' },
      { status: 'In Review', user: 'David Lee', date: '2026-08-16T09:30:00', note: 'Cross-checking with service contract' },
    ],
  },
  {
    id: 'bill-1030',
    billNumber: 'INV-1030',
    vendor: 'Blue Harbor Catering',
    category: 'Operations',
    amount: 820.4,
    status: 'Approved',
    billingDate: '2026-08-08',
    submittedBy: 'Olivia Park',
    description: 'Client event catering and beverages',
    documents: ['blue-harbor-catering.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Olivia Park', date: '2026-08-08T13:00:00', note: 'Vendor invoice uploaded for processing' },
      { status: 'Approved', user: 'Alicia Morgan', date: '2026-08-09T14:00:00', note: 'Approved due to event approval record' },
    ],
  },
  {
    id: 'bill-1031',
    billNumber: 'INV-1031',
    vendor: 'Civic Labs',
    category: 'Software',
    amount: 1420.75,
    status: 'Processing',
    billingDate: '2026-08-17',
    submittedBy: 'Priya Shah',
    description: 'Data platform support plan',
    documents: ['civic-labs-support.pdf'],
    timeline: [
      { status: 'Submitted', user: 'Priya Shah', date: '2026-08-17T08:00:00', note: 'Support renewal bill submitted' },
      { status: 'Processing', user: 'System', date: '2026-08-17T09:15:00', note: 'Document validation in progress' },
    ],
  },
]

export const mockDashboardSummary = {
  totalBills: 45,
  pendingBills: 12,
  paidBills: 28,
  overdueBills: 5,
  totalAmount: 12750.5,
  pendingAmount: 3250.75,
  paidAmount: 8950.0,
  overdueAmount: 549.75,
}

export const mockRecentActivity = [
  {
    id: '1',
    type: 'bill_paid',
    title: 'Bill Paid',
    description: 'Horizon Travel invoice INV-1028 was released for payment',
    timestamp: '2026-08-17T10:30:00',
    icon: 'checkCircle',
  },
  {
    id: '2',
    type: 'bill_uploaded',
    title: 'Bill Uploaded',
    description: 'Riverbank Telecom invoice INV-1029 was added to the queue',
    timestamp: '2026-08-16T14:15:00',
    icon: 'upload',
  },
  {
    id: '3',
    type: 'alert_overdue',
    title: 'Approval Review',
    description: 'Blue Harbor Catering invoice INV-1030 was approved by finance',
    timestamp: '2026-08-15T09:00:00',
    icon: 'alertTriangle',
  },
  {
    id: '4',
    type: 'bill_due_soon',
    title: 'Document Follow-up',
    description: 'Summit Office Supply invoice INV-1027 requires PO validation',
    timestamp: '2026-08-14T08:00:00',
    icon: 'calendar',
  },
]

export const mockUsers = [
  {
    id: 'u-001',
    name: 'Alicia Morgan',
    email: 'admin@teamenergy.com',
    role: 'Admin',
    status: 'Active',
    department: 'Finance',
    lastLogin: '2026-08-18',
  },
  {
    id: 'u-002',
    name: 'David Lee',
    email: 'approver@teamenergy.com',
    role: 'Approver',
    status: 'Active',
    department: 'Accounts Payable',
    lastLogin: '2026-08-17',
  },
  {
    id: 'u-003',
    name: 'Priya Shah',
    email: 'staff@teamenergy.com',
    role: 'Staff/User',
    status: 'Active',
    department: 'Operations',
    lastLogin: '2026-08-16',
  },
  {
    id: 'u-004',
    name: 'Lucas Barnes',
    email: 'viewer@teamenergy.com',
    role: 'Viewer',
    status: 'Inactive',
    department: 'Procurement',
    lastLogin: '2026-08-10',
  },
]

export const mockSettingsTabs = ['Profile', 'Account', 'Security', 'Notifications', 'Organization']

export const mockAlerts = [
  {
    id: '1',
    title: 'Overdue Bill',
    description: 'Internet Service bill BILL-003 ($89.99) is overdue by 15 days',
    type: 'critical',
    status: 'unread',
    dueDate: '2024-02-01',
    billId: '3',
    createdAt: '2024-01-15T10:00:00',
  },
  {
    id: '2',
    title: 'Payment Due Tomorrow',
    description: 'Electric Company bill BILL-001 ($1,250.50) is due tomorrow',
    type: 'warning',
    status: 'read',
    dueDate: '2024-02-15',
    billId: '1',
    createdAt: '2024-01-14T16:00:00',
  },
  {
    id: '3',
    title: 'New Bill Uploaded',
    description: 'Gas Company bill BILL-004 has been successfully uploaded',
    type: 'info',
    status: 'read',
    dueDate: '2024-02-25',
    billId: '4',
    createdAt: '2024-01-13T11:30:00',
  },
  {
    id: '4',
    title: 'Weekly Summary',
    description: 'You have 3 bills due this week with a total of $2,560.74',
    type: 'info',
    status: 'unread',
    dueDate: null,
    billId: null,
    createdAt: '2024-01-15T09:00:00',
  },
]

export const mockUser = {
  id: '1',
  email: 'user@example.com',
  name: 'John Doe',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  company: 'Tech Corp',
  role: 'Manager',
  phone: '+1 (555) 123-4567',
  joinedDate: '2023-01-15',
}

export const mockChartData = {
  billsOverTime: [
    { month: 'Jan', value: 3200 },
    { month: 'Feb', value: 2800 },
    { month: 'Mar', value: 3500 },
    { month: 'Apr', value: 3000 },
    { month: 'May', value: 4200 },
    { month: 'Jun', value: 3800 },
  ],
  billsByStatus: [
    { name: 'Paid', value: 28 },
    { name: 'Pending', value: 12 },
    { name: 'Overdue', value: 5 },
  ],
  billsByVendor: [
    { vendor: 'Electric Company', amount: 1250.5 },
    { vendor: 'Water Authority', amount: 320.75 },
    { vendor: 'Gas Company', amount: 450.25 },
    { vendor: 'Internet Service', amount: 89.99 },
    { vendor: 'Property Management', amount: 2500.0 },
  ],
}

export const mockNotifications = [
  {
    id: '1',
    message: 'Your bill has been processed',
    type: 'success',
    timestamp: new Date().toISOString(),
  },
  {
    id: '2',
    message: 'New payment received',
    type: 'info',
    timestamp: new Date().toISOString(),
  },
  {
    id: '3',
    message: 'Urgent: Bill payment overdue',
    type: 'error',
    timestamp: new Date().toISOString(),
  },
]
